import { PrismaClient, Categoria, Status } from "@prisma/client";

const prisma = new PrismaClient();

const cover = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn.replace(/-/g, "")}-L.jpg`;

async function main() {
  await prisma.emprestimo.deleteMany();
  await prisma.livro.deleteMany();

  await prisma.livro.createMany({
    data: [
      {
        titulo: "O Senhor dos Anéis",
        autor: "J.R.R. Tolkien",
        isbn: "978-8578274566",
        editora: "HarperCollins",
        ano: 2001,
        quantidade_total: 5,
        quantidade_disponivel: 3,
        categoria: Categoria.Romance,
        foto_url: cover("978-0618640157"),
      },
      {
        titulo: "Clean Code",
        autor: "Robert C. Martin",
        isbn: "978-0132350884",
        editora: "Prentice Hall",
        ano: 2008,
        quantidade_total: 4,
        quantidade_disponivel: 2,
        categoria: Categoria.Tecnologia,
        foto_url: cover("978-0132350884"),
      },
      {
        titulo: "O Pequeno Príncipe",
        autor: "Antoine de Saint-Exupéry",
        isbn: "978-8522458820",
        editora: "Geração Editorial",
        ano: 2015,
        quantidade_total: 6,
        quantidade_disponivel: 6,
        categoria: Categoria.Infantil,
        foto_url: cover("978-0156013987"),
      },
      {
        titulo: "Sapiens",
        autor: "Yuval Noah Harari",
        isbn: "978-8535922936",
        editora: "Companhia das Letras",
        ano: 2015,
        quantidade_total: 3,
        quantidade_disponivel: 1,
        categoria: Categoria.Historia,
        foto_url: cover("978-0062316097"),
      },
      {
        titulo: "Breve História do Tempo",
        autor: "Stephen Hawking",
        isbn: "978-8580576085",
        editora: "Intrínseca",
        ano: 2015,
        quantidade_total: 3,
        quantidade_disponivel: 3,
        categoria: Categoria.Ciencias,
        foto_url: cover("978-0553380163"),
      },
      {
        titulo: "The Pragmatic Programmer",
        autor: "Andrew Hunt",
        isbn: "978-0135957059",
        editora: "Addison-Wesley",
        ano: 2019,
        quantidade_total: 2,
        quantidade_disponivel: 0,
        categoria: Categoria.Tecnologia,
        foto_url: cover("978-0135957059"),
      },
      {
        titulo: "Dom Casmurro",
        autor: "Machado de Assis",
        isbn: "978-8572328197",
        editora: "Martin Claret",
        ano: 2010,
        quantidade_total: 4,
        quantidade_disponivel: 4,
        categoria: Categoria.Romance,
        foto_url: cover("978-8535910841"),
      },
      {
        titulo: "A Origem das Espécies",
        autor: "Charles Darwin",
        isbn: "978-8572328685",
        editora: "Martin Claret",
        ano: 2014,
        quantidade_total: 2,
        quantidade_disponivel: 2,
        categoria: Categoria.Ciencias,
        foto_url: cover("978-0140432053"),
      },
      {
        titulo: "Design Patterns",
        autor: "Gang of Four",
        isbn: "978-0201633610",
        editora: "Addison-Wesley",
        ano: 1994,
        quantidade_total: 3,
        quantidade_disponivel: 1,
        categoria: Categoria.Tecnologia,
        foto_url: cover("978-0201633610"),
      },
      {
        titulo: "Refactoring",
        autor: "Martin Fowler",
        isbn: "978-0134757599",
        editora: "Addison-Wesley",
        ano: 2018,
        quantidade_total: 2,
        quantidade_disponivel: 2,
        categoria: Categoria.Tecnologia,
        foto_url: cover("978-0134757599"),
      },
      {
        titulo: "A Guerra dos Tronos",
        autor: "George R. R. Martin",
        isbn: "978-8544100882",
        editora: "Leya",
        ano: 2010,
        quantidade_total: 4,
        quantidade_disponivel: 2,
        categoria: Categoria.Romance,
        foto_url: cover("978-0553573404"),
      },
      {
        titulo: "Harry Potter e a Pedra Filosofal",
        autor: "J.K. Rowling",
        isbn: "978-8532530783",
        editora: "Rocco",
        ano: 2000,
        quantidade_total: 6,
        quantidade_disponivel: 4,
        categoria: Categoria.Infantil,
        foto_url: cover("978-8532530783"),
      },
      {
        titulo: "O Hobbit",
        autor: "J.R.R. Tolkien",
        isbn: "978-8578271220",
        editora: "HarperCollins",
        ano: 2013,
        quantidade_total: 4,
        quantidade_disponivel: 4,
        categoria: Categoria.Romance,
        foto_url: cover("978-0261102217"),
      },
      {
        titulo: "1984",
        autor: "George Orwell",
        isbn: "978-8535914849",
        editora: "Companhia das Letras",
        ano: 2009,
        quantidade_total: 5,
        quantidade_disponivel: 3,
        categoria: Categoria.Romance,
        foto_url: cover("978-8535914849"),
      },
      {
        titulo: "Cosmos",
        autor: "Carl Sagan",
        isbn: "978-8535929225",
        editora: "Companhia das Letras",
        ano: 2017,
        quantidade_total: 3,
        quantidade_disponivel: 3,
        categoria: Categoria.Ciencias,
        foto_url: cover("978-8535929225"),
      },
      {
        titulo: "O Mundo de Sofia",
        autor: "Jostein Gaarder",
        isbn: "978-8522413041",
        editora: "Martins Fontes",
        ano: 2012,
        quantidade_total: 3,
        quantidade_disponivel: 2,
        categoria: Categoria.Infantil,
        foto_url: cover("978-0374528256"),
      },
      {
        titulo: "Yuval Noah Harari: 21 Lições",
        autor: "Yuval Noah Harari",
        isbn: "978-8535931785",
        editora: "Companhia das Letras",
        ano: 2018,
        quantidade_total: 4,
        quantidade_disponivel: 4,
        categoria: Categoria.Historia,
        foto_url: cover("978-8535931785"),
      },
      {
        titulo: "Uma Breve História de Quase Tudo",
        autor: "Bill Bryson",
        isbn: "978-8535902273",
        editora: "Companhia das Letras",
        ano: 2006,
        quantidade_total: 2,
        quantidade_disponivel: 0,
        categoria: Categoria.Ciencias,
        foto_url: cover("978-0767908184"),
      },
      {
        titulo: "O Nome do Vento",
        autor: "Patrick Rothfuss",
        isbn: "978-8599296639",
        editora: "Arqueiro",
        ano: 2009,
        quantidade_total: 3,
        quantidade_disponivel: 1,
        categoria: Categoria.Romance,
        foto_url: cover("978-0756404079"),
      },
      {
        titulo: "Estruturas de Dados e Algoritmos",
        autor: "Thomas H. Cormen",
        isbn: "978-8535236996",
        editora: "Campus",
        ano: 2012,
        quantidade_total: 3,
        quantidade_disponivel: 3,
        categoria: Categoria.Tecnologia,
        foto_url: cover("978-0262033848"),
      },
      {
        titulo: "Revolução dos Bichos",
        autor: "George Orwell",
        isbn: "978-8535909555",
        editora: "Companhia das Letras",
        ano: 2007,
        quantidade_total: 5,
        quantidade_disponivel: 5,
        categoria: Categoria.Romance,
        foto_url: cover("978-0451526342"),
      },
      {
        titulo: "O Alquimista",
        autor: "Paulo Coelho",
        isbn: "978-8501073419",
        editora: "HarperCollins",
        ano: 1988,
        quantidade_total: 6,
        quantidade_disponivel: 5,
        categoria: Categoria.Romance,
        foto_url: cover("978-0061122415"),
      },
      {
        titulo: "Contato",
        autor: "Carl Sagan",
        isbn: "978-8535929294",
        editora: "Companhia das Letras",
        ano: 2014,
        quantidade_total: 2,
        quantidade_disponivel: 2,
        categoria: Categoria.Ciencias,
        foto_url: cover("978-8535929294"),
      },
      {
        titulo: "Homo Deus",
        autor: "Yuval Noah Harari",
        isbn: "978-8535928075",
        editora: "Companhia das Letras",
        ano: 2016,
        quantidade_total: 3,
        quantidade_disponivel: 2,
        categoria: Categoria.Historia,
        foto_url: cover("978-0062464316"),
      },
      {
        titulo: "Alice no País das Maravilhas",
        autor: "Lewis Carroll",
        isbn: "978-8572328197",
        editora: "Zahar",
        ano: 2013,
        quantidade_total: 4,
        quantidade_disponivel: 4,
        categoria: Categoria.Infantil,
        foto_url: cover("978-0147515872"),
      },
    ],
  });

  const livros = await prisma.livro.findMany({ orderBy: { createdAt: "asc" } });

  const hoje = new Date();
  const diasAtras = (n: number) => new Date(hoje.getTime() - n * 86400000);
  const diasFrente = (n: number) => new Date(hoje.getTime() + n * 86400000);

  await prisma.emprestimo.createMany({
    data: [
      {
        livroId: livros[0].id,
        nome_cliente: "Ana Paula Silva",
        email_cliente: "ana.silva@email.com",
        data_locacao: diasAtras(10),
        data_prevista_devolucao: diasFrente(4),
        status: Status.Em_andamento,
      },
      {
        livroId: livros[0].id,
        nome_cliente: "Carlos Mendes",
        email_cliente: "carlos.mendes@email.com",
        data_locacao: diasAtras(20),
        data_prevista_devolucao: diasAtras(6),
        status: Status.Atrasado,
      },
      {
        livroId: livros[1].id,
        nome_cliente: "Fernanda Costa",
        email_cliente: "fernanda.costa@email.com",
        data_locacao: diasAtras(5),
        data_prevista_devolucao: diasFrente(9),
        status: Status.Em_andamento,
      },
      {
        livroId: livros[1].id,
        nome_cliente: "Rafael Oliveira",
        email_cliente: "rafael.oliveira@email.com",
        data_locacao: diasAtras(30),
        data_prevista_devolucao: diasAtras(16),
        status: Status.Devolvido,
      },
      {
        livroId: livros[3].id,
        nome_cliente: "Juliana Martins",
        email_cliente: "juliana.martins@email.com",
        data_locacao: diasAtras(3),
        data_prevista_devolucao: diasFrente(11),
        status: Status.Em_andamento,
      },
      {
        livroId: livros[3].id,
        nome_cliente: "Bruno Souza",
        email_cliente: "bruno.souza@email.com",
        data_locacao: diasAtras(15),
        data_prevista_devolucao: diasAtras(1),
        status: Status.Atrasado,
      },
      {
        livroId: livros[5].id,
        nome_cliente: "Mariana Lima",
        email_cliente: "mariana.lima@email.com",
        data_locacao: diasAtras(8),
        data_prevista_devolucao: diasFrente(6),
        status: Status.Em_andamento,
      },
      {
        livroId: livros[5].id,
        nome_cliente: "Pedro Alves",
        email_cliente: "pedro.alves@email.com",
        data_locacao: diasAtras(25),
        data_prevista_devolucao: diasAtras(11),
        status: Status.Devolvido,
      },
    ],
  });

  console.log("✅ Seed concluído com sucesso");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
